### ISSUE TITLE
after higlass-ingest, can't see the file in the browser

### ISSUE THREAD

**Issue by vivekbhr** [higlass/higlass-docker#160]
Hello

I wanted to use higlass with my own bed file. I think I sucessfully ran the inject from inside docker using this command:

```
(inside docker): python higlass-server/manage.py ingest_tileset --filename TADs_domains.bed --filetype bedfile --datatype bedlike
```

But `curl http://localhost:8989/api/v1/tileset_info/?d=$ID` gives me

```
{"FxhE9-xlTDGZ7gIcxBHC8g": {"error": "Unknown filetype bedfile", "name": "TADs_domains.bed", "datatype": "bedlike", "coordSystem": "", "coordSystem2": ""}}
```
And I can't see the file on server.. What am I doing wring here?

**Comment by pkerpedjiev** [comment]
You have to aggregate the file to beddb format. See here: http://docs.higlass.io/data_preparation.html#bed-files

**Comment by vivekbhr** [comment]
Hi @pkerpedjiev . Unfortunately I am getting the same error after following the instructions there too.. Am I supposed to change the `--filetype` or `--datatype` arguments ?

**Comment by pkerpedjiev** [comment]
Ah yes, if you've aggregated using clodius, you should be ingesting the beddb file using `--filetype beddb --datatype bedlike`

**Comment by vivekbhr** [comment]
it works now. thanks :+1:
