### ISSUE TITLE
export images

### ISSUE THREAD

**Issue by astrovsky01** [higlass/higlass-docker#163]
I'm trying to make some modifications to the method of export of images in a running higlass container, but editing hglib.min.js is not actually affecting the files in any way (currently just renaming export.* to helloworld.* via sed). Is there something I'm missing? I don't see any other call for export, and the sources say I'm editing the file being called.
Thanks!

**Comment by pkerpedjiev** [comment]
Could you be more specific about what you're trying to do? 

Are you editing hglib.min.js in the docker container?

**Comment by astrovsky01** [comment]
I'm working on adding higlass as a tool in Galaxy. Eventually, I need to be able let data flow between a running higlass container and galaxy, but right now, I'm just trying to make the output go to a different location than the downloads folder, so that I can have Galaxy retrieve it into the analysis history.
And yes, I edited it inside the container -- it doesn't exist as a standalone file in any higlass repo until the container starts up.

**Comment by pkerpedjiev** [comment]
It might be a cache issue?

We also do something like that in `higlass-manage`. Take a look here to see if that's helpful: https://github.com/higlass/higlass-manage/blob/master/higlass_manage/start.py#L417

As a side note, the download to the Downloads folder is handled by the browser. The higlass client just tells the browser that there's something to download.

**Comment by astrovsky01** [comment]
It was absolutely a cache issue -- running in incognito fixed it right up, thanks!
And in that case, I'll see if I can get around using just download() and output some other way.

I really appreciate the help!
